# Generated by Django 5.2.8 on 2025-11-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
